services:
  - mysql
matrix:
  include:
    - language: rust
      rust: nightly
      before_script:
        - cd backend
      script:
        - cat ~travis/.my.cnf
        - RUST_BACKTRACE=full cargo test
