services:
  - mysql
matrix:
  include:
    - language: rust
      rust: nightly
      before_script:
        - cd backend
      script:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
        # - RUST_BACKTRACE=full cargo test
